version: '3.4'

services:
    vue:
        build:
            context: .
            args:
                - API_URL=${API_URL}
                - Mail__SupportMailAddress=${Mail__SupportMailAddress}
        ports:
            - 8080:80